[workspace]
authors = ["bsennblad <bengt.sennblad@scilifelab.se>"]
channels = ["conda-forge", "bioconda"]
name = "redmine_utils"
platforms = ["linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[target.linux.tasks]
rstudio = "rstudio"

[target.osx.tasks]
#rstudio = "open -a rstudio"
rstudio = "/Applications/RStudio.app/Contents/MacOS/RStudio"

[dependencies]
python = ">=3.14.0,<3.15"
quarto = ">=1.8.25,<2"
r-base = ">=4.5.1,<4.6"
r-reticulate = ">=1.43.0,<2"
r-knitr = ">=1.50,<2"
pandas = ">=2.3.3,<3"
yaml = ">=0.2.5,<0.3"
r-kableextra = ">=1.4.0,<2"
requests = ">=2.32.5,<3"
pyyaml = ">=6.0.3,<7"
